version: "3"

services:
  umbrellanotice:
    build:
      context: .
      dockerfile: Dockerfile.ci
    environment:
      TZ: Asia/Tokyo
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - socket-data:/umbrellanotice/tmp/sockets
    depends_on:
      - mysql
      - redis
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - umbrellanotice
      - redis
    volumes:
      - socket-data:/umbrellanotice/tmp/sockets
    command: sidekiq
  redis:
    build:
      context: docker/redis
      dockerfile: Dockerfile.ci
    volumes:
      - socket-data:/run/redis
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/mysql/mysql-confd:/etc/mysql/conf.d
    ports:
      - '33306:3306'
  nginx:
    build:
      context: docker/nginx
    volumes:
      - socket-data:/umbrellanotice/tmp/sockets
    ports:
      - 80:80
    depends_on:
    - umbrellanotice

volumes:
  socket-data: