version: "3"

services:
  umbrellanotice:
    build:
      context: .
      dockerfile: Dockerfile.ci
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - nginx
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '33306:3306'
    volumes:
      - ./docker/myslq/mysql-confd:/etc/mysql/conf.d
  nginx:
    build:
      context: docker/nginx
    ports:
      - 80:80