version: "3"

services:
  umbrellanotice:
    build:
      context: .
      dockerfile: docker/umbrellanotice/Dockerfile
    environment:
      TZ: Asia/Tokyo
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - socket-data:/umbrellanotice/tmp/sockets
    depends_on:
      - mysql
      - redis
    comma: circleci
  sidekiq:
    build:
      context: .
      dockerfile: docker/umbrellanotice/Dockerfile
    environment:
      TZ: Asia/Tokyo
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
    depends_on:
      - umbrellanotice
      - redis
    volumes:
      - socket-data:/umbrellanotice/tmp/sockets
    command: sidekiq
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    volumes:
      - socket-data:/run/redis
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile.ci
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '33306:3306'
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - socket-data:/umbrellanotice/tmp/sockets
    ports:
      - 80:80
    depends_on:
    - umbrellanotice

volumes:
  socket-data: