version: "3"

services:
  umbrellanotice:
    build:
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - nginx
    command: bundle exec unicorn_rails -c /umbrellanotice/config/unicorn.rb -E development
  mysql:
    image: mysql:8.0
    env_file:
      - ./docker/environments/mysql.env
    ports:
      - '33306:3306'
    volumes:
      - ./docker/myslq/mysql-confd:/etc/mysql/conf.d
  nginx:
    build:
      context: docker/nginx
    ports:
      - 80:80