version: '3'
services:
  umbrellanotice:
    build:
      context: .
    env_file:
      - ./environments/mysql.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/umbrellanotice
      - public-data:/umbrellanotice/public
      - tmp-data:/umbrellanotice/tmp
      - log-data:/umbrellanotice/log
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    env_file:
      - ./environments/mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/umbrellanotice/public
      - tmp-data:/umbrellanotice/tmp
    ports:
      - 80:80
    depends_on:
      - umbrellanotice

volumes:
  public-data:
  tmp-data:
  log-data:
  mysql-data:
