version: '3'

services:
  umbrellanotice:
    build:
      context: ./backend
      dockerfile: ./docker/umbrellanotice/Dockerfile
    environment:
      TZ:         Asia/Tokyo
      LINE_ID:    $LINE_ID
      LINE_TOKEN: $LINE_TOKEN
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./backend:/umbrellanotice
      - public-data:/umbrellanotice/public
      - tmp-data:/umbrellanotice/tmp
      - log-data:/umbrellanotice/log
      - socket-data:/umbrellanotice/tmp/sockets
    depends_on:
      - mysql
      - redis
    tty: true
    stdin_open: true
  sidekiq:
    build:
      context: ./backend
      dockerfile: ./docker/umbrellanotice/Dockerfile
    volumes:
      - ./backend:/umbrellanotice
      - public-data:/umbrellanotice/public
      - tmp-data:/umbrellanotice/tmp
      - log-data:/umbrellanotice/log
      - socket-data:/umbrellanotice/tmp/sockets
    depends_on:
      - umbrellanotice
      - redis
    command: sidekiq
  redis:
    build:
      context: ./backend
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - socket-data:/run/redis
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./backend/docker/mysql/mysql-confd:/etc/mysql/conf.d
  nginx:
    build:
      context: ./backend
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - socket-data:/umbrellanotice/tmp/sockets
    ports:
      - 80:80
      - 443:443
    depends_on:
      - umbrellanotice

volumes:
  public-data:
  tmp-data:
  log-data:
  socket-data:
