version: '3.8'

services:

  rails:
    build:
      context: ./backend
      dockerfile: ./docker/rails/Dockerfile
    environment:
      TZ:         Asia/Tokyo
      LINE_ID:    $LINE_ID
      LINE_TOKEN: $LINE_TOKEN
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./backend:/rails-app
      - bundler-libs:/rails-app/vendor/bundle
      - public-data:/rails-app/public
      - log-data:/rails-app/log
      - socket-data:/rails-app/tmp/sockets
    tmpfs: /rails-app/tmp
    depends_on:
      - mysql
      - redis
    tty: true
    stdin_open: true

  sidekiq:
    build:
      context: ./backend
      dockerfile: ./docker/rails/Dockerfile
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./backend:/rails-app
      - bundler-libs:/rails-app/vendor/bundle
      - public-data:/rails-app/public
      - log-data:/rails-app/log
      - socket-data:/rails-app/tmp/sockets
    tmpfs: /rails-app/tmp
    depends_on:
      - rails
      - redis
    command: sidekiq

  redis:
    build:
      context: ./backend
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - socket-data:/run/redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./backend/docker/mysql/mysql-confd:/etc/mysql/conf.d

  nginx:
    build:
      context: ./frontend
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - socket-data:/tmp/sockets
    ports:
      - 80:80
      - 443:443
    depends_on:
      - rails

  next:
    build:
      context: ./frontend
      dockerfile: ./docker/next/Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./frontend:/next-app:cached
      - node-modules:/next-app/node_modules
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    tty: true
    stdin_open: true

volumes:
  public-data:
  log-data:
  socket-data:
  node-modules:
  bundler-libs:
  yarn-cache:
