version: '3'

services:
  umbrellanotice:
    build:
      context: .
    env_file:
      - ./docker/environments/mysql.env
      - ./docker/environments/omni_facebook.env
    volumes:
      - .:/umbrellanotice
    depends_on:
      - mysql
    tty: true
  mysql:
    image: mysql:8.0
    env_file:
      - ./docker/environments/mysql.env
    volumes:
      - ./docker/mysql/mysql-confd:/etc/mysql/conf.d
    cap_add:
      - SYS_NICE
  nginx:
    build:
      context: docker/nginx
    ports:
      - 80:80
    depends_on:
      - umbrellanotice