default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { ENV['MYSQL_ROOT_PASSWORD'] } %>
  host: mysql

development:
  <<: *default
  database: umbrellanotice_development

test:
  <<: *default
  database: umbrellanotice_test

production:
  <<: *default
  database: umbrellanotice_production
  username: ENV['DB_USER_NAME']
  password: ENV['DB_PASSWORD']
  host:     ENV['DB_HOST']
  port:     ENV['DB_PORT']